version: '3'

networks:
  cms:

services:
  nginx:
    image: nginx:stable
    container_name: cms-nginx
    ports:
      - ${APP_PORT:-8000}:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - cms

  php:
    image: thomasveen/larawhale-package:7.4
    container_name: cms-php
    volumes:
      - .:/var/www/html
    networks:
      - cms

  mysql:
    image: mysql:5.7
    container_name: cms-mysql
    tmpfs: /var/lib/mysql
    restart: unless-stopped
    ports:
      - ${DB_PORT_LOCAL:-33060}:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - cms
