version: '3'

networks:
  cms:

services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    networks:
      - cms
